version: '3'
services:
 db:
   image: mysql:latest
   container_name: mysql
   ports:
     - "3306:3306"
   environment:
     - MYSQL_ROOT_PASSWORD=mglFuture7
     - MYSQL_DATABASE=mgldefi
   volumes:
     - /Users/szabolcs/Documents/Personal/Freelancing/stotatek-db/db:/var/lib/mysql 